# Generated by Django 4.2.16 on 2025-11-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workload',
            name='hours',
        ),
        migrations.AddField(
            model_name='workload',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='core.studygroup'),
        ),
        migrations.AddField(
            model_name='workload',
            name='pair_slot',
            field=models.CharField(blank=True, choices=[('1', '1 пара (09:00–10:35)'), ('2', '2 пара (10:45–12:20)'), ('3', '3 пара (13:00–14:35)'), ('4', '4 пара (14:45–17:15)'), ('5', '5 пара (16:30–18:05)'), ('6', '6 пара (18:15–19:50)')], max_length=1, verbose_name='Пара'),
        ),
    ]
